name = "ControlSystemIdentification"
uuid = "3abffc1c-5106-53b7-b354-a47bfc086282"
authors = ["baggepinnen <baggepinnen@gmail.com>"]
version = "2.5.1"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
LowLevelParticleFilters = "d9d29d28-c116-5dba-9239-57a5fe23875b"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
MonteCarloMeasurements = "0987c9cc-fe09-11e8-30f0-b96dd679fdca"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
TotalLeastSquares = "028f657a-7ace-5159-a694-8cfd97933b0c"

[compat]
ComponentArrays = "0.8, 0.9, 0.10, 0.11, 0.12, 0.13"
ControlSystemsBase = "1"
DSP = "0.6.1, 0.7"
FFTW = "1.1"
FillArrays = "<0.9, 0.9, 0.11, 0.12, 0.13"
ForwardDiff = "0.10"
LowLevelParticleFilters = "2.0, 3.0"
MatrixEquations = "1.1, 2.0"
MonteCarloMeasurements = "1.0"
Optim = "<0.20, 0.20, 0.21, 0.22, 1.0"
Parameters = "<0.13"
QuadGK = "2.4"
RecipesBase = "<0.8, 0.8, 1.0"
StatsBase = "0.33"
TotalLeastSquares = "1.7.2"
julia = "1.6"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
